name: Python app to Azure Web App

on:
  push:
    branches:
      - hrb_dev_branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Actions'
      uses: actions/checkout@v3

    - name: 'Set up Python'
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: 'Install dependencies'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 'Azure WebApp Deploy'
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'hrb-dataapp'  # Replace with your Azure Web App name
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
